[pytest]
minversion = 7.0
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers
markers =
    smoke: Mark test as smoke test
    regression: Mark test as regression test
    user: Mark test as user endpoint test
